In [18]:
print('anjul')


anjul


In [19]:
X=3
Y=3.0
X is Y
X==Y


True

In [20]:
X is Y

x=3
y=3
x is y

x=input('whats your name : ')
print(x)

s=['1',2,2,3,4]
s

whats your name : anjul
anjul


['1', 2, 2, 3, 4]

In [ ]:
s='0000anjul000'
s.strip('0')

'anjul'

In [ ]:
x=input('enter 1st : ' )
y=input('enter 2nd : ')
z=input('enter 3rd : ')

def sslit(a1,a2,a3):
    p=a1+a2+a3
    for i in range(0,50):
        t1=p[i]
        t2=p[i+1]
        if(t1==t2):
            s[i]=t1
            s[i+1]=t2
        
        s[i]=p[i]
        return(s)

print(sslit(x,y,z))
        


In [1]:
import numpy as np


In [2]:
x=np.array([1,2,3])



In [3]:
print(type(x))

print(x.shape)

<class 'numpy.ndarray'>
(3,)


In [4]:
print(x[2])

3


In [5]:
x[1]=5

print(x)

[1 5 3]


In [6]:
y=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])

In [7]:
print(y.shape)

(3, 4)


In [8]:
print(y
     )

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]


In [9]:
print(type(y
          ))

<class 'numpy.ndarray'>


In [10]:
zeroo= np.zeros((3,3))

In [11]:
print(zeroo
     )

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [12]:
oncess=np.ones((3,3))

In [13]:
print(oncess)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [14]:
same = np.full((2,2),4.0)

In [15]:
print(same
     )

[[ 4.  4.]
 [ 4.  4.]]


In [16]:
dig=np.eye(4,4)

In [17]:
print(dig)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [18]:
print(dig.shape)

(4, 4)


In [19]:
np.random.random((2,2))

array([[ 0.25940776,  0.56620017],
       [ 0.6315687 ,  0.74331218]])

In [20]:
random.random((3,3))

NameError: name 'random' is not defined

In [21]:
a=np.array([[1,2,3],[4,5,6]])

In [22]:
s=a[0:2 , 1:3]

In [23]:
print(s
     
    )

[[2 3]
 [5 6]]


In [24]:
new_loc=np.array(a[0:2 , 1:3])

In [25]:
print(new_loc)

[[2 3]
 [5 6]]


 # boolean array

In [26]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
filter=(a>5)
filter

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [36]:
a[filter]


array([6, 7, 8, 9])

In [33]:
a[a>5]

array([6, 7, 8, 9])

In [35]:
a[(a>=4) & (a<8)]

array([4, 5, 6, 7])

In [41]:
a[a%2==0] +=100
a


array([[  1, 402,   3],
       [404,   5, 406],
       [  7, 408,   9]])

# data type conversion

In [43]:
a=np.array([1,2,3])

print(a.dtype)

int64


In [45]:
b=np.array([1.2, 3.4, 5.6])

print(b.dtype)

float64


In [53]:
c=np.array([1.2, 3.4], dtype=np.int)
print(c
    )

[1 3]


can be also write int64 insted of int

In [54]:
d=np.array([1,2,3],dtype=np.float)
print(d.dtype)

float64


In [51]:
print(d)

[ 1.  2.  3.]


# arithmatic oprations

In [55]:
#add operation 

x=np.array([1,2,3])
y=np.array([1.1, 2.2, 3.3])

print(x+y)
print()
print(np.add(x,y))

#both are correct

[ 2.1  4.2  6.3]

[ 2.1  4.2  6.3]


In [56]:
#subtraction 

print(x-y)
print()
print(np.subtract(x,y))

[-0.1 -0.2 -0.3]

[-0.1 -0.2 -0.3]


In [59]:
#multiplication

print(x*y)
print(np.multiply(x,y))

[ 1.1  4.4  9.9]
[ 1.1  4.4  9.9]


In [76]:
#divide n squre root
#can be done both ways

print(y/x)
print(np.divide(x,y))




[ 1.          0.70710678  0.57735027]
[ 1.          1.41421356  1.73205081]


In [67]:
#exponent
#e**x

print(np.exp(x))

[  2.71828183   7.3890561   20.08553692]


# analytics, sorting

In [78]:
a=10*np.random.randn(2,5)
print(a)

[[ 10.98689035  21.64163447  -1.74399726  10.49165547   7.51414967]
 [-19.29564537   2.88401915   0.97045681  -1.80817252  -9.00476264]]


In [79]:
#mean
print(a.mean())

2.26362281428


In [80]:
#compute the mean by row
print(a.mean(axis=1))

[ 9.77806654 -5.25082091]


In [81]:
#mean by col
print(a.mean(axis=0))

[ -4.15437751  12.26282681  -0.38677022   4.34174148  -0.74530648]


In [82]:
#sum
print(a.sum())

22.6362281428


In [83]:
#median by rows
print(np.median(a,axis=1))

[ 10.49165547  -1.80817252]


In [85]:
#median by column
print(np.median(a,axis=0))

[ -4.15437751  12.26282681  -0.38677022   4.34174148  -0.74530648]


# sorting

In [86]:
s=np.random.randn(12)

In [87]:
print(s)

[ 1.03528711  0.57906405  1.26222681  0.65427472 -0.22504819  0.25206218
 -1.73463486  0.26992323 -0.05126206 -0.8762891   1.18084167  0.73890379]


In [96]:
sorted=np.array(s)
sorted.sort()
print(sorted)

[-1.73463486 -0.8762891  -0.22504819 -0.05126206  0.25206218  0.26992323
  0.57906405  0.65427472  0.73890379  1.03528711  1.18084167  1.26222681]


# unique elements

In [99]:
p=np.array([1,2,3,4,1,2,3,1,2,1])

In [101]:
print(np.unique(p))

[1 2 3 4]


In [102]:
p=np.unique(p)
p

array([1, 2, 3, 4])

# set operations


In [104]:
a=np.array(['a','b','c'])
b=np.array(['d','a','b'])
print(a,",",b)

['a' 'b' 'c'] , ['d' 'a' 'b']


In [110]:
print(np.intersect1d(a,b))

['a' 'b']


In [111]:
print(np.union1d(a,b))

['a' 'b' 'c' 'd']


In [114]:
print(np.setdiff1d(a,b))
#which is not present in b

['c']


In [115]:
print(np.in1d(a,b))
#false means that's not in b

[ True  True False]


# broadcasting

In [119]:
z=np.zeros([4,3])
z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [120]:
a=np.array([1,2,3])

In [123]:
p=z+a
p

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [130]:
b=np.array([[1,2,3,4]])

In [133]:
b=b.T    #transpose
b


array([[1],
       [2],
       [3],
       [4]])

In [135]:
q=z+b
q

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.]])

In [136]:
s=np.array([1])

In [138]:
sb=z+s
sb

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [140]:
sb=sb+1
sb

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])